### ISSUE TITLE
Is there any support for oauth?

### ISSUE THREAD

**Issue by manbat** [k33g/gh3#22]
Using oauth would get a lot more tokens before my IP address gets blocked!

**Comment by leivaburto** [comment]
Hi @manbat . I hope is not too late to help you with this. 

As you can see in the [closed issues](https://github.com/k33g/gh3/issues?q=is%3Aissue+is%3Aclosed) there is no "builtin" support nor documentation and @k33g recommends to use [github.js](https://github.com/michael/github) instead for such cases. 

Nevertheless, If you don't want to get blocked from the Github API, you could set up a token on your own ([Settings -> Applications](https://github.com/settings/applications) -> Personal access tokens -> Generate new token). Once you have a token, you could modify gh3.js wherever there is that you are using it and add an authorization header.

```javascript
beforeSend : function(xhr){
	xhr.setRequestHeader('Authorization','token 123456secret123456');
}, 
```

For example, if you want to get the repos from an user with an authenticated call, add the function "beforeSend", [like this](https://gist.github.com/leivaburto/b091640d8a7b180dc2aa) (gh3.js, line 930).

You should do this **only if you are sure no one will get access to your token**, since creating a token and using it in a public place could allow anyone to get that token and act on your behalf (on github), **so be careful with that!**

**Comment by galeksandrp** [comment]
Request can be modified here.

```javascript
Gh3.Helper = Kind.extend({

	},{
		protocol : "https",
		domain : "api.github.com",
		callHttpApi : function (apiParams) {
```

You can add `Authorizaton: oauth TOKEN` or use `client_id` and `client_secret` of dummy app because of https://developer.github.com/v3/#increasing-the-unauthenticated-rate-limit-for-oauth-applications.

#6 #19

**Comment by k33g** [comment]
:+1:
